name: PR Run

env:
  AWS_DEFAULT_REGION: "eu-central-2"
  REPO_NAME: ${{ github.event.repository.name }}
  DOCKER_BUILD_SUMMARY: false

on:
  workflow_call:
    inputs:
      repo_name:
        description: 'Name of the repository'
        required: true
        type: string
      base_ref:
        description: 'Base branch reference of the pull request'
        required: true
        type: string
      head_ref:
        description: 'Head branch reference of the pull request'
        required: true
        type: string

jobs:
  VALIDATE:
    runs-on: ubuntu-24.04
    outputs:
      proceed: ${{ steps.setup.outputs.proceed }}
      deploy: ${{ steps.setup.outputs.deploy }}
      environment: ${{ steps.setup.outputs.environment }}
      deployment_list: ${{ steps.setup.outputs.deployment_list }}
      tag_suffix: ${{ steps.setup.outputs.tag_suffix }}
      tag_sha: ${{ steps.setup.outputs.tag_sha }}
      build_matrix: ${{ steps.setup.outputs.build_matrix }}
      needs_utils: ${{ steps.setup.outputs.needs_utils }}
      db_migration_submodule: ${{ steps.setup.outputs.db_migration_submodule }}
    steps:
    - name: Checkout ci repo
      uses: actions/checkout@v4
      with:
        repository: krama/ci
        path: .
        token: ${{ secrets.CHECKOUT_TOKEN }}
        ref: main

    - name: Install jq
      run: |
        if [ "$RUNNER_OS" == "Linux" ]; then
          if command -v apt-get &> /dev/null; then
            sudo apt-get update && sudo apt-get install -y jq
          elif command -v dnf &> /dev/null; then
            sudo dnf install -y jq
          else
            echo "Unsupported Linux distribution"
            exit 1
          fi
        else
          echo "$RUNNER_OS not supported"
          exit 1
        fi
      shell: bash

    - name: Run setup and validation script
      id: setup
      shell: bash
      env:
        REGISTRY: ${{ secrets .REGISTRY }}
        GITHUB_EVENT_NAME: ${{ github.event_name }}
        GITHUB_EVENT_PATH: ${{ github.event_path }}
        RAW_REPO_NAME: ${{ github.event.repository.name }}
      run: |
        SHORT_NAME="${RAW_REPO_NAME##*/}"
        bash .github/scripts/setup_env.sh \
          --repo_name "$SHORT_NAME" \
          --head_ref "${{ inputs.head_ref }}" \
          --base_ref "${{ inputs.base_ref }}" \
          --sha "${{ github.event.pull_request.head.sha }}" \
          --config ".github/config/env.json" \
          --registry "${REGISTRY}"
        echo "Script outputs:"
        cat $GITHUB_OUTPUT

    - name: Add build summary
      if: ${{ always() }}
      run: |
        echo "| Branch | Env |" >> $GITHUB_STEP_SUMMARY
        echo "| ------ | --- |" >> $GITHUB_STEP_SUMMARY
        echo "| ${{ inputs.head_ref }} | ${{ steps.setup.outputs.environment }}" >> $GITHUB_STEP_SUMMARY

  BUILD:
    runs-on: ubuntu-24.04
    needs: [ VALIDATE ]
    if: ${{ needs.VALIDATE.outputs.proceed == 'true' }}
    strategy:
      matrix: ${{ fromJson(needs.VALIDATE.outputs.build_matrix) }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: false
        ref: ${{ inputs.base_ref }}

    - name: Checkout utils repo
      if: ${{ needs.VALIDATE.outputs.needs_utils == 'true' }}
      uses: actions/checkout@v4
      with:
        repository: krama/utils
        path: app/src/utils
        token: ${{ secrets.CHECKOUT_TOKEN }}
        ref: ${{ inputs.base_ref }}

    - name: Checkout migration repo
      if: ${{ needs.VALIDATE.outputs.db_migration_submodule == 'true' }}
      uses: actions/checkout@v4
      with:
        repository: krama/migrations
        path: app/db_migrations
        token: ${{ secrets.CHECKOUT_TOKEN }}
        ref: ${{ inputs.base_ref }}

    - name: Copy utils for admin-tools
      if: ${{ github.event.repository.name == 'admin-tools' }}
      run: cp -R app/src/utils client/src/

    - name: Copy utils for db_migration in promotion
      if: ${{ needs.VALIDATE.outputs.db_migration_submodule == 'true' }}
      run: |
        cp -R app/src/utils app/db_migrations/app/src/utils && cp app/db_migrations/app/tsconfig.build.json app/db_migrations/app/tsconfig.json

    - name: Install tree
      run: |
        if [ "$RUNNER_OS" == "Linux" ]; then
          if command -v apt-get &> /dev/null; then
            sudo apt-get update && sudo apt-get install -y tree
          elif command -v dnf &> /dev/null; then
            sudo dnf install -y tree
          else
            echo "Unsupported Linux distribution"
            exit 1
          fi
        else
          echo "$RUNNER_OS not supported"
          exit 1
        fi
      shell: bash

    - name: Tree
      run: tree -h -L 6 .

    - name: Login to Harbor
      uses: docker/login-action@v3
      with:
        registry: ${{ secrets.REGISTRY }}
        username: ${{ secrets.REGISTRY_USER }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.17.0'

    - name: SonarQube Scan
      if: ${{ github.event.repository.name != 'easy-casino' }}
      uses: sonarsource/sonarqube-scan-action@master
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      with:
        args: >
          -Dsonar.projectKey="${{ secrets.SONAR_PROJECT_KEY }}" -Dsonar.branch.name="${{ github.base_ref || github.ref_name }}<---${{ github.head_ref || github.ref_name }}"

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        driver-opts: |
          image=${{ secrets.REGISTRY }}/ci-images/moby/buildkit:latest
          network=host

    - name: Set up Python for Docker Squash
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    - run: pip install -q docker-squash

    - name: Set Docker tags from script outputs
      run: |
        CONTEXT_PATH=""
        if [ "${{ matrix.context }}" != "." ] && [ -n "${{ matrix.context }}" ]; then
            echo "IMAGE_TAG=${{ secrets.REGISTRY }}/casino/${{ env.REPO_NAME }}/${{ matrix.context }}:${{ needs.VALIDATE.outputs.tag_suffix }}" >> $GITHUB_ENV
            echo "IMAGE_TAG_SHA=${{ secrets.REGISTRY }}/casino/${{ env.REPO_NAME }}/${{ matrix.context }}:${{ needs.VALIDATE.outputs.tag_sha }}" >> $GITHUB_ENV
        else
            echo "IMAGE_TAG=${{ secrets.REGISTRY }}/casino/${{ env.REPO_NAME }}:${{ needs.VALIDATE.outputs.tag_suffix }}" >> $GITHUB_ENV
            echo "IMAGE_TAG_SHA=${{ secrets.REGISTRY }}/casino/${{ env.REPO_NAME }}:${{ needs.VALIDATE.outputs.tag_sha }}" >> $GITHUB_ENV
        fi

    - name: Build Docker image
      run: |
        docker build \
          -t ${{ env.REPO_NAME }}:${{ needs.VALIDATE.outputs.tag_suffix }}-nonsquashed \
          ${{ matrix.context }}

    - name: Squash image
      run: docker-squash -t ${{ env.IMAGE_TAG }} ${{ env.REPO_NAME }}:${{ needs.VALIDATE.outputs.tag_suffix }}-nonsquashed

    - name: Push Docker image
      run: |
        docker push ${{ env.IMAGE_TAG }}
        docker tag ${{ env.IMAGE_TAG }} ${{ env.IMAGE_TAG_SHA }}
        docker push ${{ env.IMAGE_TAG_SHA }}

  DEPLOY:
    runs-on: ubuntu-24.04
    needs: [ VALIDATE, BUILD ]
    if: ${{ needs.VALIDATE.outputs.deploy == 'true' }}
    timeout-minutes: 5
    continue-on-error: false
    strategy:
      matrix:
        deployment: ${{ fromJson(needs.VALIDATE.outputs.deployment_list) }}
    steps:
    - name: Set Environment Variables
      run: |
        echo "NAMESPACE=${{ matrix.deployment.namespace }}" >> $GITHUB_ENV
        echo "CLUSTER_NAME=${{ matrix.deployment.cluster_name }}" >> $GITHUB_ENV
        echo "PROJECT=${{ matrix.deployment.project }}" >> $GITHUB_ENV
        echo "ENVIRONMENT=${{ matrix.deployment.environment }}" >> $GITHUB_ENV

    - name: Overwrite REPO_NAME for casino projects
      run: |
        if [ "${REPO_NAME}" = "imogene" ]; then
          case "$PROJECT" in
            "alice") echo "REPO_NAME=alice" >> $GITHUB_ENV ;;
            "tweedles") echo "REPO_NAME=tweedles" >> $GITHUB_ENV ;;
            "caterpillar") echo "REPO_NAME=caterpillar" >> $GITHUB_ENV ;;
          esac
        else
          echo "Not easy-casino. Skipping step."
        fi

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets[format('{0}', matrix.deployment.aws_credentials.access_key_id)] }}
        aws-secret-access-key: ${{ secrets[format('{0}', matrix.deployment.aws_credentials.secret_access_key)] }}
        aws-region: ${{ env.AWS_DEFAULT_REGION }}

    - name: Install AWS CLI and kubectl
      run: |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        sudo ./aws/install --update
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        chmod +x kubectl
        sudo mv kubectl /usr/local/bin/

    - name: Generate KUBECONFIG
      run: |
        aws eks update-kubeconfig --name ${{ env.CLUSTER_NAME }} --region ${{ env.AWS_DEFAULT_REGION }} --kubeconfig ~/.kube/config

    - name: Set Kubeconfig Context
      run: |
        echo "CONTEXT=$(kubectl config current-context --kubeconfig ~/.kube/config)" >> $GITHUB_ENV

    - name: Check if application exists in tenjokers cluster
      run: |
        # Only run the check for tenjokers cluster
        if [[ "${{ env.CLUSTER_NAME }}" == *"tenjokers"* ]]; then
          echo "Tenjokers cluster detected. Checking if application ${{ env.REPO_NAME }} exists..."
          if kubectl --context=$CONTEXT get deployment/${{ env.REPO_NAME }} -n ${{ env.NAMESPACE }} --kubeconfig ~/.kube/config &>/dev/null; then
            echo "Application ${{ env.REPO_NAME }} exists in tenjokers cluster. Proceeding with deployment."
            echo "APP_EXISTS=true" >> $GITHUB_ENV
          else
            echo "Application ${{ env.REPO_NAME }} does not exist in tenjokers cluster. Skipping deployment."
            echo "APP_EXISTS=false" >> $GITHUB_ENV
          fi
        else
          echo "Not a tenjokers cluster. Proceeding with deployment without checking."
          echo "APP_EXISTS=true" >> $GITHUB_ENV
        fi

    - name: Restart Deployment and Check Status
      if: ${{ env.APP_EXISTS == 'true' }}
      run: |
        kubectl --context=$CONTEXT rollout restart deployment/${{ env.REPO_NAME }} -n ${{ env.NAMESPACE }} --kubeconfig ~/.kube/config
        if kubectl --context=$CONTEXT rollout status deployment/${{ env.REPO_NAME }} -n ${{ env.NAMESPACE }} --kubeconfig ~/.kube/config; then
          echo "Deployment successful!"
        else
          echo "Deployment failed or timed out. Waiting 90 seconds before checking status..."
          sleep 90
          echo "Checking deployment status and logs..."
          kubectl --context=$CONTEXT get pods -n ${{ env.NAMESPACE }} --kubeconfig ~/.kube/config | sed 's/\(*_PASSWORD\|*_USER\)=[^ ]*/\1=********/g'
          kubectl --context=$CONTEXT describe deployment/${{ env.REPO_NAME }} -n ${{ env.NAMESPACE }} --kubeconfig ~/.kube/config | sed -E 's/(*_PASSWORD|*_USER):[[:space:]]+[^[:space:]]*/\1: ********/g'
          kubectl --context=$CONTEXT logs --all-containers -l app=${{ env.REPO_NAME }} -n ${{ env.NAMESPACE }} --kubeconfig ~/.kube/config || true
          exit 1
        fi

    - name: Log Skipped Deployment
      if: ${{ env.APP_EXISTS == 'false' }}
      run: |
        echo "Deployment skipped because application ${{ env.REPO_NAME }} does not exist in tenjokers cluster."

  NOTIFICATION:
    name: Notification
    needs: [ VALIDATE, BUILD, DEPLOY ]
    if: ${{ always() && (needs.VALIDATE.result == 'failure' || needs.BUILD.result == 'failure' || needs.DEPLOY.result == 'failure') }}
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout CI repository
      uses: actions/checkout@v4
      with:
        repository: krama/ci
        path: .
        token: ${{ secrets.CHECKOUT_TOKEN }}
        ref: refactoring

    - name: Generate Rocket.Chat JSON
      id: generate_notification
      run: |
        chmod +x .github/scripts/notification.sh

        REPO="${{ inputs.repo_name }}"
        [ -z "$REPO" ] && REPO="${GITHUB_REPOSITORY#*/}"

        BRANCH="${{ inputs.build_branch }}"
        [ -z "$BRANCH" ] && BRANCH="${{ github.ref_name }}"

        ENVIRONMENT="${{ inputs.environment }}"
        [ -z "$ENVIRONMENT" ] && ENVIRONMENT="${{ needs.VALIDATE.outputs.environment }}"

        WORKFLOW_URL="${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}"

        VALIDATE_STATUS="${{ needs.VALIDATE.result }}"
        BUILD_STATUS="${{ needs.BUILD.result }}"
        DEPLOY_STATUS="${{ needs.DEPLOY.result }}"

        # Сохраняем результат в файл и сам файл
        .github/scripts/notification.sh \
          "$REPO" \
          "$GITHUB_ACTOR" \
          "$BRANCH" \
          "$ENVIRONMENT" \
          "$WORKFLOW_URL" \
          "$VALIDATE_STATUS" \
          "$BUILD_STATUS" \
          "$DEPLOY_STATUS" > /tmp/rocket_payload.json

        echo "payload_path=/tmp/rocket_payload.json" >> $GITHUB_OUTPUT

    - name: Send Rocket.Chat notification
      run: |
        PAYLOAD_PATH="${{ steps.generate_notification.outputs.payload_path }}"

        jq '.attachments[0].mrkdwn = true' "$PAYLOAD_PATH" > /tmp/modified_payload.json

        echo "Sending Rocket.Chat payload with markdown enabled:"
        cat /tmp/modified_payload.json

        curl -X POST -H 'Content-Type: application/json' \
          --data @"/tmp/modified_payload.json" \
          "https://rocket.skeleton.services/hooks/${{ secrets.ROCKET_NOTIFICATION_ID }}/${{ secrets.ROCKET_API_NOTIFICATION_PR }}"
